### ISSUE TITLE
Its not an issue but need help in sending outlook mail using powershell script

### ISSUE THREAD

**Issue by vishnuprakash9845** [mayurhirlekar/powershell-automation#2]
I am an automation engineer

I have have automated few test cases and getting the test results. This test results I wanted to forward to team using outlook using powershell. I tried many ways to do it, but not working. 

I want an powershell script to send outlook mail to people who I configure.

Can anyone please help me out in this.

**Comment by mayurhirlekar** [comment]
Hi,

Have you tried send-mailmessage cmdlet ? Just make sure SmtpServer parameter / $PSEmailServer is correctly set up. 
remember you need to have proper credentials to use the Smtp Server

.Net World 
See Examples 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-7.1

Another useful resource to check how other people are doing it 
https://gallery.technet.microsoft.com/scriptcenter/site/search?f%5B0%5D.Type=RootCategory&f%5B0%5D.Value=messaging&f%5B0%5D.Text=Messaging%20%26%20Communication

Code:
https://stackoverflow.com/questions/36355271/how-to-send-email-with-powershell

Python (Info and explanation in somewhat details)
https://automatetheboringstuff.com/2e/chapter18/

hope this info is useful. Good luck :) 

Thanks
